### ISSUE TITLE
Destructive vs non-destructive changes between two files

### ISSUE THREAD

**Issue by isvaljek** [mmanela/diffplex#10]
Is there a way to detect whether file changes between old and new file version were destructive or non-destructive?
Non destructive would be text addition, and destructive would be overwrites and deletions.

**Comment by mmanela** [comment]
I believe if you look at the DiffBlock models if one of those contains deletions on the file you don't want destroyed then it indicates a destructive change.

**Comment by isvaljek** [comment]
Thanks,

I have two more questions: 
*on some diffblocks there are sometimes deleteCountA 0 and deleteStartA of non zero, how come?
0: DeleteCountA: 3, DeleteStartA: 7
0: InsertCountB: 1, InsertStartB: 7
1: DeleteCountA: 0, DeleteStartA: 39
1: InsertCountB: 1, InsertStartB: 37

*can you give me a brief example how would one go about merging two files based on CreateLineDiffs with no deletions detected?

**Comment by mmanela** [comment]
It means nothing was changed on that side of the diff I believe.
