### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by Drake53** [mmanela/diffplex#102]
Would you consider adding back .NET 5 as a supported target framework?
This is mainly for DiffPlex.Wpf, since DiffPlex still supports .NET 5 through .NET standard 2.0

**Comment by mmanela** [comment]
You can still grab older versions of the library for support. But given only a couple people contribute to this, its tough to have a larger testing matrix.

**Comment by Drake53** [comment]
Since I was having issues with the WPF control I made my own WinForms control: https://github.com/Drake53/Area53/blob/master/src/Area53.WinForms/Controls/SideBySideDiffView.cs
This way I only need a dependency on the core library as well, which has .NET standard support, so my request is no longer relevant. Thanks anyways.
