### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by yukozh** [mmanela/diffplex#104]
Hi All,

 I want to compare 2 streams bytes, however, I didn't see InlineDiffBuilder has method to accept 2 streams to generate diff. The 2 streams are very large which will greater than 1GB. So read all bytes into memory is not a good choice. 

Any suggestions?

BR,
Yuko

**Comment by mmanela** [comment]
This is not a supported scenario. I think a large stream diff will require a different algorithm than this library uses.
