### ISSUE TITLE
Support .NET 4.5 and forward

### ISSUE THREAD

**Issue by giggio** [mmanela/diffplex#11]
Please support .NET 4.5, 4.5.1, 4.5.2 and 4.6.

**Comment by ryanlin1986** [comment]
+1

**Comment by mmanela** [comment]
Does Chutzpah not run on those? It should run fine.Is there an issue?

''
Now a PCL (portable library) that targets .NET 4.0, Silverlight 5.0, Windows 8.0, Windows Phone 8.0, Windows Phone Appx 8.1. '''

**Comment by giggio** [comment]
Chutzpah does not provide any libraries, only tools, so it should install fine. Where did you get this message, @mmanela?

**Comment by mmanela** [comment]
That is the comment I included on the release notes when I fixed the targeting :)

**Comment by mmanela** [comment]
And Chutzpah *does* contain a library.

**Comment by mmanela** [comment]
But back to the question at hand. If I already target 4.0 do I need to change anything?

**Comment by giggio** [comment]
Chutzpah only provides tools:

![chutz](https://cloud.githubusercontent.com/assets/334958/11105134/242dd780-88b4-11e5-9f96-dc017bfecb55.png)

For it to provide libraries, it would need a `lib` folder.

You need to include .NET 4.5. First test against it, then update your nuspec files to include it. I don't think you can support 4.5 and 4.0 on the same binary, if you want to continue to support .NET 4.0 you probably need to build more than once, once for each target.

**Comment by riyadparvez** [comment]
Does not support Mono.

Below is the output: 
> 
Attempting to gather dependency information for package 'DiffPlex.1.3.0' with respect to project 'diffplex.test', targeting '.NETFramework,Version=v4.5'
  GET https://api.nuget.org/v3/registration1-gz/diffplex/index.json
  OK https://api.nuget.org/v3/registration1-gz/diffplex/index.json 63ms
Total number of results gathered : 1
Gathering dependency information took 67.17 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	65.98 ms
Attempting to resolve dependencies for package 'DiffPlex.1.3.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'DiffPlex.1.3.0'
Resolved actions to install package 'DiffPlex.1.3.0'
Retrieving package 'DiffPlex 1.3.0' from 'nuget.org'.
For adding package 'DiffPlex.1.3.0' to project 'diffplex.test' that targets 'net45'.
Install failed. Rolling back...
Package 'DiffPlex.1.3.0' does not exist in project 'diffplex.test'
Package 'DiffPlex.1.3.0' does not exist in folder '/Users/riyad/Desktop/gmail/packages'
Executing nuget actions took 126.99 ms
Could not install package 'DiffPlex 1.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mmanela** [comment]
Can you share what commands you ran and how? (I am new to mono).

**Comment by riyadparvez** [comment]
I've used from GUI of VS for Mac preview. If I set target framework of the project to "Mono / .NET Framework 4.5" and try to install DiffPlex through nuget, I see the above error.

**Comment by mmanela** [comment]
I am targeted .netstandard 1.4. What does mono support?

**Comment by riyadparvez** [comment]
I've tried to install diffplex on: https://dotnetfiddle.net/. Couldn't install diffplex there. Although, it might be an issue on their end.

BTW, you can try setting up online continuous build. Travis CI offers Mono support and Appveyor offers Windows support. Here are examples of config files needed for Travis and Appveyor: https://github.com/jstedfast/MimeKit/blob/master/.travis.yml and https://github.com/jstedfast/MimeKit/blob/master/appveyor.yml.
