### ISSUE TITLE
What the interface IChunker is?

### ISSUE THREAD

**Issue by hjy1210** [mmanela/diffplex#138]
I am using nuget DiffPlex.WPF(1.4.0) with DiffPLex(1.7.2). In Object Browser window, we can see interface IChunker has single method:
`string[] Chunk(string text)`.

In this site, IChunker has single method:
`IReadOnlyList<string> Chunk(string text)`

In the future nuget, will  `string[] Chunk(string text)`  change to `IReadOnlyList<string> Chunk(string text)` ?

**Comment by hjy1210** [comment]
Move to IReadOnlyList Commits on Jul 13, 2024.

**Comment by Aurelien-Dev** [comment]
test
