### ISSUE TITLE
Wrong side by side comparison

### ISSUE THREAD

**Issue by MrStepson** [mmanela/diffplex#15]
It seems there are few issues with word-breaks processing (tested with side-by-side web UI):
1. Compare “**Hello,·World!**“ with “**Hello!**” – whole “old text” (“**Hello,·World!**”) is marked as _Deleted_. But actually “**Hello**” should be marked as “_Unchanged_”,  “**,·World**” as deleted and “**!**” as Unchanged.
2. Compare “**Hello,·World!**“ with “**Hi, Wordl!**” – “**Hello,**” is marked as Modified (comma included), but whould be better if only “**Hello**” is marked “_Modified_” and “**, World**” unchanged.

**Comment by riyadparvez** [comment]
Yes. This bug is still there.

**Comment by mmanela** [comment]
I have a fix for this. Will get it out soon.

**Comment by mmanela** [comment]
Released on 1.4
