### ISSUE TITLE
Install via nugget on .net 4.5.2 throws 

### ISSUE THREAD

**Issue by jupagose** [mmanela/diffplex#22]
Can't install 'DiffPlex 1.4.0' package, into a project target to .NETFramework, Version=v4.5.2, but the package doesn't contains assembly references or compatible files to it.

**Comment by mmanela** [comment]
Chutzpah is targeting netstandard 1.4 which means the min .net framework is 4.6.1

**Comment by mmanela** [comment]
If you take the older version it should work on that framework https://www.nuget.org/packages/DiffPlex/1.2.1

**Comment by jupagose** [comment]
Tks. :)
