### ISSUE TITLE
Is it possible to also target net45?

### ISSUE THREAD

**Issue by drewnoakes** [mmanela/diffplex#23]
I would like to upgrade from 1.2.1 to 1.4.0, but my project targets `net45` which isn't covered by `netstandard1.4`.

Is there a way to maintain support for `net45`? Are there any APIs you'd miss out on? If so, can they be worked around without excessive changes?

I maintain a [library that targets `net35`, `net45` and `netstandard1.3`](https://www.nuget.org/packages/MetadataExtractor/2.0.0-rc2) and need only a few `#if` directives to achieve this.

If there's interest and no reason this can't be done, I should be able to find time to make a PR.

**Comment by mmanela** [comment]
There is no reason this can't be done, it might already be fine for 1.3. If you are interested take a stab at it and I will gladly accept.

**Comment by drewnoakes** [comment]
Good to hear. I'll take a shot as time permits.

Not sure if you were suggesting that 1.3 would support .NET 4.5. If so, FYI, `netstandard1.3` covers `net46`, not `net45` or `net451`.

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by mmanela** [comment]
We could try to 1.2 :)

**Comment by drewnoakes** [comment]
Actually there was nothing stopping the core library dropping to `netstandard1.0`. That's enough for my purposes, though it should be possible to add `net35` if needed, or other platforms.

**Comment by mmanela** [comment]
I merged and will try to publish new version soon

**Comment by mmanela** [comment]
I published version 1.4.1 (and also your change finally made me go set up an appveyor build for this project )

**Comment by drewnoakes** [comment]
Great, I'll test it out. Thanks for the quick turnaround.
