### ISSUE TITLE
.NET 4.5+ Framework support 

### ISSUE THREAD

**Issue by MistyKuu** [mmanela/diffplex#28]
Any chance of releasing .NET framework version side by side with .NET standard? There is a bug in last .NET framework version.

**Comment by mmanela** [comment]
@MistyKuu I thought you can use .netstandard from .net framework?

**Comment by MistyKuu** [comment]
Yes I can but if I reference it from framework it adds about 20 dependencies from nets tankard and I don't want to include them

**Comment by mmanela** [comment]
Sure, I am not against multi-targeting but I do not have time to play with it right now. I would gladly accept a PR if you wanted to.

**Comment by MistyKuu** [comment]
Can I build it myself from your sources and use it or is it against your license?

**Comment by VahidN** [comment]
You can use `dotnet pack` to do it automatically
```xml
  <TargetFrameworks>net35;net40;net45;net46;netstandard1.0;netstandard1.3</TargetFrameworks>    

  <Target Name="PostcompileScript" AfterTargets="Build" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="dotnet pack --no-build --configuration $(Configuration)" />
  </Target>
```
