### ISSUE TITLE
Incorrect Result

### ISSUE THREAD

**Issue by bansalhoney** [mmanela/diffplex#30]
Hi,

I am working on a windows application where I am comparing word by word of two strings. I used SideBySideDiffBuilder.BuildDiffModel to get the comparison result.

Sometimes, what happens is even if the word is same in both the strings at a particular position, it shows as word has been deleted in second string and it continues like this for some words untill it finds same word at later stage in the second string.

**Comment by bansalhoney** [comment]
I am running the app for unicode font Punjabi (India).

**Comment by mmanela** [comment]
Can you give an example? A file of text I can use?
