### ISSUE TITLE
Won't build, stating .NET Framework 3.5 can't be found

### ISSUE THREAD

**Issue by setagana** [mmanela/diffplex#32]
Hi there,

I'd really like to use this package but I can't, for love nor money get it to build. Whenever I try to build the Diffplex project from Visual Studio 2017 I get an error saying .NET Framework 3.5 or higher needs to be installed. My system has both .NET Framework 4.7 and .NET Core 1.1.0 installed, I have verified this through a registry check for the Framework and dotnet --version for Core.

Googling the error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3645	.NET Framework v3.5 Service Pack 1 was not found. In order to target ".NETFramework,Version=v3.5", .NET Framework v3.5 Service Pack 1 or later must be installed.	DiffPlex	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1122	

Results in only one topic: https://github.com/Microsoft/msbuild/issues/1333 In there I found the comment:

> What's the work-around for people who need to build such projects on VS 2017? I just ran into this today, and the only thing I could figure out was to compile on a separate machine with only VS 2015 installed.

So I spun up a clean Windows 10 VM and installed Visual Studio 2015 and tried to build it there, but that failed miserably because 2015 can't work with the Core .csproj format.

If you have any suggestions on how I can get this to work I would be most grateful!

**Comment by mmanela** [comment]
Try deleting net35 from [DiffPlex.csproj](https://github.com/mmanela/diffplex/blob/master/DiffPlex/DiffPlex.csproj)

**Comment by setagana** [comment]
That seems to have done the trick, thanks!
