### ISSUE TITLE
Result not what I expected

### ISSUE THREAD

**Issue by dekenless** [mmanela/diffplex#36]
<img width="613" alt="bad" src="https://user-images.githubusercontent.com/10144906/40753415-824f8fb0-6463-11e8-8a62-e1b5b959951a.PNG">

Below is from Notepad++ using the Compare plug in (this is the result I would expect):
<img width="739" alt="good" src="https://user-images.githubusercontent.com/10144906/40753436-a9ddcdc6-6463-11e8-9a89-5ea264f5e65f.PNG">

Attached are the sample files.  Any thoughts?
[2a.txt](https://github.com/mmanela/diffplex/files/2055989/2a.txt)
[1a.txt](https://github.com/mmanela/diffplex/files/2055990/1a.txt)

**Comment by YVEF** [comment]
Hello @dekenless , your attachments are different from those you showed.
I compare your files through diffplex and several online text comparers, and I got the same result.
Could you provide another examples with invalid result?
