### ISSUE TITLE
Question about use

### ISSUE THREAD

**Issue by jaswicki** [mmanela/diffplex#40]
I am trying to use the side by side comparison in my project. Currently my project lets the user select 2 GPOs from a list and it presents them in side by side WebBrowser controls. I would then want them to be marked up to show the differences in the 2 policies.

I know this has been around a while but are there any good examples that can be referenced? I am stuck and really don't want to reinvent the wheel if this would do the job.

I have added a reference to the DiffPlex dll but I don't see how to actually get the comparison accomplished.

**Comment by mmanela** [comment]
Take a look at the WebDiffer sample

**Server Side**
https://github.com/mmanela/diffplex/blob/master/WebDiffer/Controllers/DiffController.cs

**Client Side**
https://github.com/mmanela/diffplex/blob/master/WebDiffer/Controllers/DiffController.cs

**Comment by jaswicki** [comment]
I can't even get that to run. Are there any Windows Forms examples?

**Comment by JamesSkemp** [comment]
So I needed to implement this in a Windows Forms app for my job.

What would be the best way to share the code for a simple Windows Forms application demo? (I haven't written one yet; the implementation for work is pretty specific to our needs.)

**Comment by mmanela** [comment]
Ideally it would be a simple sample app that we can include in the repo. Otherwise, we could just author a wiki page
