### ISSUE TITLE
Any example for winform?

### ISSUE THREAD

**Issue by chuki2** [mmanela/diffplex#51]
Do you have any example for winform?

Thanks in advance

**Comment by VPKSoft** [comment]
Hi,
I made a class library containing a Windows Forms [control](https://github.com/VPKSoft/ScintillaDiff).
This is for [Scintilla](https://github.com/jacobslusser/ScintillaNET) though 🙄

**Comment by mmanela** [comment]
That is awesome @VPKSoft . If you want to, please send a PR to add a section on the README of Diffplex to link to your cool work.

**Comment by VPKSoft** [comment]
I'll do that if I have the time - anyhow, thanks for the great library! 👍

**Comment by kingcean** [comment]
@chuki2 You can add an `ElementHost` control (in `System.Windows.Forms.Integration` namespace and you can find it in Toolbox of Visual Studio) into your form and set its `Child` property as one of `DiffViewer`, `SideBySideDiffViewer` and `InlineDiffViewer` (in `DiffPlex.Wpf.Controls` namespace of `DiffPlex.Wpf` assembly).

![image](https://user-images.githubusercontent.com/1724940/77877918-aa366900-7289-11ea-96c9-63e81b512a46.png)

**Comment by kingcean** [comment]
@mmanela I think you can close this issue since I have sent PR for demo as well as I post the comment here a year before.

**Comment by mmanela** [comment]
Merged!
