### ISSUE TITLE
Word Level Diffing in the SideBySideDiffViewer WPF Control

### ISSUE THREAD

**Issue by DavidJSnyder** [mmanela/diffplex#53]
Is there a way to do Word level diffing in the SideBySideDiffViewer WPF Control that I'm missing, or does that only support line level?

**Comment by mmanela** [comment]
@kingcean Can you help?

**Comment by kingcean** [comment]
@mmanela OK.

**Comment by kingcean** [comment]
Hi @DavidJSnyder You can update `DiffPlex.Wpf` to version `1.1.1` which we have enabled word level diffing in `SideBySideDiffViewer` and `DiffViewer` by default.

**Comment by DavidJSnyder** [comment]
Thanks, I will try it.
