### ISSUE TITLE
Question: What does ChangeType.Imaginary means?

### ISSUE THREAD

**Issue by bessgeor** [mmanela/diffplex#63]
As in subject. `Deleted`, `Inserted`, `Modified` and `Unchanged` are pretty intuitive, but I can't get what does `ChangeType.Imaginary` means i.e. in what cases line change is "Imaginary"?

**Comment by mmanela** [comment]
It represents the grey "imaginary" lines on the left side of this image. Basically, there isn't a change on the left doc, but the space is added to match to the right. 
![image](https://user-images.githubusercontent.com/304410/92266922-dab3ac00-ee94-11ea-998d-c28987423f71.png)

**Comment by bessgeor** [comment]
Thanks, that makes sense
