### ISSUE TITLE
Not expected result

### ISSUE THREAD

**Issue by boukenka** [mmanela/diffplex#73]
Hello,

I am doing the following :

```C#
string oldText ="<revision>1<revision>";
string newText = "<revision>2</revision>";
SideBySideDiffBuilder sideBySideDiffBuilder = new SideBySideDiffBuilder();
SideBySideDiffModel sideBySideDiffModel = sideBySideDiffBuilder.BuildDiffModel(oldText, newText);
```

The result should be that only character '1' has been changed to '2'.
Or it is not the result.
The line of the old text is defined as deleted in the subPieces and the line of the new text is defined as inserted in the subPieces.
Could you help please? Is it by design? Is there a workaround?

PS: If ignoreWhiteSpace is set to True or False, the result remains the same.

**Comment by mmanela** [comment]
The default word separator does not consider < or > to break words (this may be a mistake but has been this way for a long time). To get around this you need to pass your own word breaker. The below code shows you how:

```C#
string oldText = "<revision>1<revision>";
string newText = "<revision>2</revision>";
char[] wordSeparaters = { ' ', '\t', '.', '(', ')', '{', '}', ',', '!', '?', ';', '<','>' };
var delimiterChunker = new DelimiterChunker(wordSeparaters);
SideBySideDiffBuilder sideBySideDiffBuilder = new SideBySideDiffBuilder(Differ.Instance, new LineChunker(), delimiterChunker);
SideBySideDiffModel sideBySideDiffModel = sideBySideDiffBuilder.BuildDiffModel(oldText, newText);
```

**Comment by boukenka** [comment]
Thank you @mmanela. I will give it a go. 😄

**Comment by boukenka** [comment]
That solved my problem. 😄 

May I suggest the following two points, please.
* Update the entire project to .NET 5.
* Add a checkbox in the WPF demo project where there is the use of the DelimiterChunker object.

Thanks again.

**Comment by mmanela** [comment]
@boukenka  Both are reasonable suggestion. Would you be interested in contributing :) PRs are gladly appreciated
