### ISSUE TITLE
Unable to use DiffPlex due to license incompatibility

### ISSUE THREAD

**Issue by jspraul** [mmanela/diffplex#8]
The Open DBDiff project received [a pull request](https://opendbiff.codeplex.com/SourceControl/network/forks/UdginPyl/openDbDiff/contribution/8080) incorporating your control (which appears to be awesome), but as best I can tell I can not accept it due to the [use of the Ms-PL license](http://programmers.stackexchange.com/questions/191123/why-isnt-the-microsoft-public-license-compatible-with-the-gpl).

Please consider changing to a license that is [GPL-compatible](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

Thanks for your time and your work on such a helpful control!

**Comment by mmanela** [comment]
I updated the license to apache

**Comment by jspraul** [comment]
Thank you much!
